### ISSUE TITLE
Setting EIP-4788 `BEACON_ROOTS_ADDRESS`

### ISSUE THREAD

**Issue by dapplion** [gnosischain/specs#16]
Contract deployment is currently spec'ed as https://eips.ethereum.org/EIPS/eip-4788#deployment

> The beacon roots contract is deployed like any other smart contract. A special synthetic address is generated by working backwards from the desired deployment transaction:

Given this deployment style, it's impossible to re-use the same `BEACON_ROOTS_ADDRESS` as Ethereum mainnet. If Gnosis adopts the same deployment style, this issue is blocked by finalizing the contract's bytecode, see
- https://github.com/gnosischain/specs/issues/15

### How to compute the deployer address

```js
const EthereumTx = require('ethereumjs-tx').Transaction;
const assert = require('assert');

const txData = {
  nonce: '0x00',
  gasPrice: '0xe8d4a51000',
  gasLimit: '0x3d090',
  to: null,  // contract creation
  value: '0x00',
  data: '0x60618060095f395ff33373fffffffffffffffffffffffffffffffffffffffe14604d57602036146024575f5ffd5b5f35801560495762001fff810690815414603c575f5ffd5b62001fff01545f5260205ff35b5f5ffd5b62001fff42064281555f359062001fff015500',
  v: '0x1b',
  r: '0x539',
  s: '0x1b9b6eb1f0'
};

const tx = new EthereumTx(txData, { chain: 'mainnet', hardfork: 'petersburg' });
const senderAddress = '0x' + tx.getSenderAddress().toString('hex');
assert.equal(senderAddress, '0x0B799C86a49DEeb90402691F1041aa3AF2d3C875'.toLowerCase());
```

**Comment by dapplion** [comment]
The transaction above is a legacy type 0, which does not mix the chainID into the signing root, thus the produced address is the same for all networks.

However, does Gnosis chain support type 0 transactions?

**Comment by filoozom** [comment]
Deployed on both chains:

- Gnosis: https://gnosis.blockscout.com/address/0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02
- Chiado: https://gnosis-chiado.blockscout.com/address/0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02

**Comment by dapplion** [comment]
- Closing for https://github.com/gnosischain/specs/pull/23
